// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5xBxUy2mmdPg_qUa0lG7NkS8PScDrs1c',
    appId: '1:552911099754:web:3798a531af7e7d44233713',
    messagingSenderId: '552911099754',
    projectId: 'qr-code-scanner-4f0e1',
    authDomain: 'qr-code-scanner-4f0e1.firebaseapp.com',
    storageBucket: 'qr-code-scanner-4f0e1.firebasestorage.app',
    measurementId: 'G-FD9EGJ8ZY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yfLFpqzHu8aX26Mox_tFrQuZGFiBRJ4',
    appId: '1:552911099754:android:ae9da5c4d5ff48a7233713',
    messagingSenderId: '552911099754',
    projectId: 'qr-code-scanner-4f0e1',
    storageBucket: 'qr-code-scanner-4f0e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnqgcFPZ393tSvXWsWd5Squ99qFBJqtZs',
    appId: '1:552911099754:ios:1ac00eb1b5c3da57233713',
    messagingSenderId: '552911099754',
    projectId: 'qr-code-scanner-4f0e1',
    storageBucket: 'qr-code-scanner-4f0e1.firebasestorage.app',
    iosBundleId: 'com.example.qrCodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnqgcFPZ393tSvXWsWd5Squ99qFBJqtZs',
    appId: '1:552911099754:ios:1ac00eb1b5c3da57233713',
    messagingSenderId: '552911099754',
    projectId: 'qr-code-scanner-4f0e1',
    storageBucket: 'qr-code-scanner-4f0e1.firebasestorage.app',
    iosBundleId: 'com.example.qrCodeScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5xBxUy2mmdPg_qUa0lG7NkS8PScDrs1c',
    appId: '1:552911099754:web:d66b642042525941233713',
    messagingSenderId: '552911099754',
    projectId: 'qr-code-scanner-4f0e1',
    authDomain: 'qr-code-scanner-4f0e1.firebaseapp.com',
    storageBucket: 'qr-code-scanner-4f0e1.firebasestorage.app',
    measurementId: 'G-K2H3VB1DFK',
  );
}
